cc_binary(
    name = "run_solution_on_all",
    srcs = ["run_solution_on_all.cpp"],
    deps = [
        "//state:state",
        "//sol:producer_based_solver",
        "//sol:first_take_action_producer"
    ]
)