package(default_visibility = ["//visibility:public"])

cc_library(
    name = "types",
    hdrs = ["types.h"]
)

cc_library(
    name = "binary",
    hdrs = ["binary.h"],
    deps = [
        ":types"
    ],
)

cc_library(
    name = "feature",
    hdrs = ["feature.h"],
    deps = [
        ":types"
    ]
)